# Licensed under the MIT License.
#
# Module manifest for module 'PackageJsonForUnity'
#
# Generated by: hanachiru
#
# Generated on: 2024-10-23
#

@{
    RootModule        = 'PackageJsonForUnity'
    ModuleVersion     = '0.1.0'
    Author            = 'hanachiru'
    Description       = 'Powershell module for manipulating package.json for Unity.'

    FunctionsToExport = @(
        'Update-Version'
    )

    CmdletsToExport   = @()

    VariablesToExport = @()

    AliasesToExport   = @()

    PrivateData       = @{

        PSData = @{
            Tags       = 'Unity'
            LicenseUri = 'https://github.com/hanachiru/PackageJsonForUnity/blob/main/LICENSE'
            ProjectUri = 'https://github.com/hanachiru/PackageJsonForUnity/'

        }
    }

    HelpInfoURI       = 'https://github.com/hanachiru/PackageJsonForUnity/blob/main/README.md'
}